language: java
jdk:
    - openjdk

addons:
    sonarcloud:
        organization: "jackbonaventura"
        token: "9ccbb04037aecbf93fece7f3c5f0dae81c85e3ad"


script: 
- ant -buildfile Calculator/build.xml
- sonar-scanner
